### ISSUE TITLE
Sponsor us

### ISSUE THREAD

**Issue by KatieFl** [TonyFlury/SuffolkCycleDjango#21] opened 2016-02-16 21:23 UTC
On sponsor ship form.  When you leave out your name, enter in other data and click save, you get the error message of 'This is a required field'  Please consider changing this to 'Name is a required field' so what you are talking about is obvious.

**Comment by TonyFlury** [comment] 2016-02-17 22:59
Definitely a bug - even without analysis of the cause. Name has to be mandatory.

**Comment by TonyFlury** [comment] 2016-03-05 17:06
Believed fixed in 0.1.0rc1 - needs to be re-tested

**Closed as completed by TonyFlury** 2016-03-05 17:06 UTC
Labels: bug, High
